GET http://localhost:8080/api/console
###

GET http://localhost:8080/api/console/1
###

GET http://localhost:8080/api/user
###

GET http://localhost:8080/api/user/1
###

GET http://localhost:8080/api/user/favGameCount/4
###

POST http://localhost:8080/api/user/createUser/Abdul/4/3
###

POST http://localhost:8080/api/user/createUser/Ahmed/1/2
###

//Fehler - serverError wegen catch
POST http://localhost:8080/api/user/createUser/Sippi/1000/2
###


WEBSOCKET ws://localhost:8080/user-socket
###